/-! Runtime test: a randomly generated scalar program (fuzzer output, fixed
seed): 14 random functions over 14 scalar types (expression trees with every
operator and conversion, loops with mutable accumulators, fuel recursion,
array folds), called 56 times with edge-value arguments.
From the round-6 adversarial reviewers, area numbers (adv6/numbers), fuzzer
gen.py, program fz/G1. -/

-- generated by gen.py seed 1
set_option maxHeartbeats 4000000
set_option maxRecDepth 4000
@[noinline] def bn (n : Nat) : Nat := n
@[noinline] def idNat (x : Nat) : Nat := x
@[noinline] def idInt (x : Int) : Int := x
@[noinline] def idUInt8 (x : UInt8) : UInt8 := x
@[noinline] def idUInt16 (x : UInt16) : UInt16 := x
@[noinline] def idUInt32 (x : UInt32) : UInt32 := x
@[noinline] def idUInt64 (x : UInt64) : UInt64 := x
@[noinline] def idUSize (x : USize) : USize := x
@[noinline] def idInt8 (x : Int8) : Int8 := x
@[noinline] def idInt32 (x : Int32) : Int32 := x
@[noinline] def idInt64 (x : Int64) : Int64 := x
@[noinline] def idFloat (x : Float) : Float := x
@[noinline] def idFloat32 (x : Float32) : Float32 := x
@[noinline] def idBool (x : Bool) : Bool := x
@[noinline] def idChar (x : Char) : Char := x

@[noinline] def f0 (p0 : Int64) (p1 : Char) : Bool :=
  (decide ((idFloat (4.9e-324 : Float)) ≤ (let v2208 : Float32 := (if ((((0.0 : Float) + (4.9e-324 : Float))).isNaN) then (3e38 : Float32) else (((1e300 : Float) - (4.9e-324 : Float))).toFloat32); ((0 : UInt64)).toFloat)))

def f1 (p0 : Float32) (p1 : Float32) (p2 : Int32) : USize :=
  let arr : Array Float := (Array.range 1).map (fun (j : Nat) => (((if (idBool (true : Bool)) then (idUInt16 (32768 : UInt16)) else (idUInt16 (0 : UInt16)))).toFloat).scaleB 3)
  let arr := arr.mapIdx (fun j x => ((if ((1 : UInt32) != (0 : UInt32)) then ((idInt64 ((-1) : Int64))).toFloat else Float.exp ((0.1 : Float)))).floor)
  arr.foldl (fun (a : USize) x => ((((1 : UInt64) &&& (18446744073709551615 : UInt64))).toUSize <<< (a &&& (a / (9223372036854775808 : USize))))) (0 : USize)

@[noinline] def f2 (p0 : Char) (fuel : Nat) : Nat :=
  match fuel with
  | 0 => ((((idNat (1 : Nat)) &&& (idNat (9223372036854775807 : Nat))) % (let v270973 : Int := (idInt ((-9223372036854775809) : Int)); (18446744073709551616 : Nat))) % (idNat (9223372036854775807 : Nat)))
  | k + 1 => if (true : Bool) then (((k).log2 ^^^ ((k) ^ (((255 : Nat)) % 70) % 340282366920938463463374607431768211507))).sqrt else f2 ((Char.ofNat (k % 1114200))) k

def f3 (p0 : Char) : Int := Id.run do
  let mut acc : Int := ((((-7) : Int) + (18446744073709551616 : Int)) % (match (if (true : Bool) then some (idInt ((-2147483649) : Int)) else none) with | some o912142 => o912142 | none => ((-9223372036854775808) : Int)))
  for it in [0:2] do
    acc := ((((match (if (false : Bool) then some acc else none) with | some o590705 => o590705 | none => (idInt ((-340282366920938463463374607431768211457) : Int))) - (let v558388 : UInt16 := (idUInt16 (0 : UInt16)); acc)) / (((idInt32 ((-1) : Int32))).toInt64).toInt) % acc)
    if (true : Bool) then
      acc := (Int.fmod (let v868751 : UInt8 := ((idBool (true : Bool))).toUInt8; acc) (((0 : Int8) + (0 : Int8))).toInt)
  return acc

@[noinline] def f4 (p0 : USize) : Int :=
  ((idInt32 (1 : Int32))).toInt

def f5 (p0 : Float32) (p1 : Char) (fuel : Nat) : Int :=
  match fuel with
  | 0 => (let v934500 : Int32 := (((idFloat ((-1e-300) : Float))).toFloat32).toInt32; (idInt ((-9223372036854775808) : Int)))
  | k + 1 => if (false : Bool) then (((idInt (18446744073709551616 : Int))) * ((((18446744073709551616 : Int)) * ((idInt ((-7) : Int))) % 340282366920938463463374607431768211507)) % 340282366920938463463374607431768211507) else f5 (p0) ((if (decide ((idInt64 ((-1) : Int64)) < ((-1) : Int64))) then (Char.ofNat (k % 1114200)) else (idChar ('Z' : Char)))) k

@[noinline] def f6 (p0 : Int) (p1 : UInt32) (p2 : Int32) (p3 : Char) : Int :=
  p0

def f7 (p0 : Int8) (p1 : Char) (p2 : Char) (p3 : UInt8) : Int :=
  let arr : Array UInt64 := (Array.range 0).map (fun (j : Nat) => (if ((if (false : Bool) then p3 else p3) == (match (if (true : Bool) then some p3 else none) with | some o653816 => p3 | none => p3)) then (((idUSize (18446744073709551615 : USize))).toUInt64 ^^^ (1 : UInt64)) else (((1 : UInt64) &&& (idUInt64 (9223372036854775808 : UInt64))) ||| ((idUSize (18446744073709551615 : USize))).toUInt64)))
  let arr := arr.mapIdx (fun j x => x)
  arr.foldl (fun (a : Int) x => ((~~~((if (idBool (false : Bool)) then (1 : Int32) else (idInt32 (0 : Int32)))))).toInt) ((let v925902 : UInt16 := (idUInt16 (32768 : UInt16)); ((-1) : Int64))).toInt

def f8 (p0 : Float32) (p1 : Float32) (fuel : Nat) : Float32 :=
  match fuel with
  | 0 => ((((idUInt32 (1 : UInt32))).toFloat - ((idFloat ((-1e-300) : Float)) / (idFloat (0.1 : Float))))).toFloat32
  | k + 1 => if (((4.9e-324 : Float)).isNaN) then (if (decide ((Char.ofNat (k % 1114200)) < (Char.ofNat (k % 1114200)))) then (((127 : Int8)).toFloat).toFloat32 else ((p0 * p0) - p0)) else f8 (p1) (((if (false : Bool) then p1 else p0) - p0)) k

def f9 (p0 : Int32) : UInt64 :=
  let arr : Array USize := (Array.range 4).map (fun (j : Nat) => (let v339411 : Nat := j; ((-((idUSize (0 : USize)))) >>> ((18446744073709551615 : UInt64)).toUSize)))
  let arr := arr.mapIdx (fun j x => (~~~((((18446744073709551615 : UInt64) ||| (idUInt64 (0 : UInt64)))).toUSize)))
  arr.foldl (fun (a : UInt64) x => (if (((1 : UInt8) != (255 : UInt8)) && (false : Bool)) then (((idFloat (0.0 : Float)) - (idFloat ((-0.0) : Float)))).toUInt64 else ((idUInt16 (1 : UInt16))).toUInt64)) (18446744073709551615 : UInt64)

@[noinline] def f10 (p0 : Int64) (p1 : UInt32) (p2 : UInt16) : Int32 :=
  ((-(((((18446744073709551616 : Int) / (idInt ((-7) : Int)))).toInt32 <<< (((idInt (9223372036854775807 : Int)) % ((-7) : Int))).toInt32))) <<< ((-((if (decide (('😀' : Char) < (idChar ('😀' : Char)))) then (if (false : Bool) then (idInt32 (1 : Int32)) else (idInt32 (2147483647 : Int32))) else (idInt32 ((-2147483648) : Int32))))) * (0 : Int32)))

@[noinline] def f11 (p0 : Float32) (p1 : Int32) (p2 : Char) (p3 : Float32) (fuel : Nat) : Int64 :=
  match fuel with
  | 0 => (((let v183790 : UInt64 := (idUInt64 (0 : UInt64)); ((-9223372036854775808) : Int64)) + ((idInt64 (0 : Int64)) <<< ((-9223372036854775808) : Int64))) % (let v263801 : UInt8 := ((0 : UInt8) / (idUInt8 (0 : UInt8))); ((idInt64 ((-1) : Int64))).abs))
  | k + 1 => if (false : Bool) then (9223372036854775807 : Int64) else f11 ((p3 - (let v242973 : UInt16 := (65535 : UInt16); p3))) ((if (decide ((idUInt64 (0 : UInt64)) < (9223372036854775808 : UInt64))) then (f10 ((idInt64 (1 : Int64))) ((0 : UInt32)) ((idUInt16 (1 : UInt16)))) else (-(p1)))) (p2) (((p3 * p0) + (p0 * p3))) k

@[noinline] def f12 (p0 : Float32) : Int32 := Id.run do
  let mut acc : Int32 := (((idInt32 (1 : Int32)) % (idInt32 (2147483647 : Int32))) + (f10 (((-9223372036854775808) : Int64)) ((2147483648 : UInt32)) ((65535 : UInt16))))
  for it in [0:10] do
    acc := ((-(((p0 / p0)).toInt32)) ^^^ (((if (true : Bool) then acc else acc) &&& (~~~((idInt32 ((-1) : Int32))))) <<< acc))
    if (!(false : Bool)) then
      acc := (if (((1 : UInt64)).toInt64 != (idInt64 (1 : Int64))) then (f10 (((-9223372036854775808) : Int64)) ((idUInt32 (0 : UInt32))) ((32768 : UInt16))) else (((7 : Nat)).toInt32 - (acc ||| (idInt32 ((-1) : Int32)))))
  return acc

@[noinline] def f13 (p0 : UInt16) (p1 : Int64) : Int8 :=
  ((if ((((((0.0/0.0) : Float)).floor / (p0).toFloat)).isNaN) then ((-340282366920938463463374607431768211457) : Int) else (idInt (2147483648 : Int)))).toInt8

def main : IO Unit := do
  IO.println s!"f0.0: {f0 (idInt64 ((-9223372036854775808) : Int64)) (idChar ('λ' : Char))}"
  IO.println s!"f0.1: {f0 (idInt64 ((-9223372036854775808) : Int64)) (idChar ('\x00' : Char))}"
  IO.println s!"f0.2: {f0 (idInt64 ((-9223372036854775808) : Int64)) (idChar ('λ' : Char))}"
  IO.println s!"f0.3: {f0 (idInt64 ((-9223372036854775808) : Int64)) (idChar ('😀' : Char))}"
  IO.println s!"f1.0: {f1 (idFloat32 (3e38 : Float32)) (idFloat32 (0.1 : Float32)) (idInt32 ((-2147483648) : Int32))}"
  IO.println s!"f1.1: {f1 (idFloat32 ((-2.25) : Float32)) (idFloat32 (3e38 : Float32)) (idInt32 ((-2147483648) : Int32))}"
  IO.println s!"f1.2: {f1 (idFloat32 (1.5 : Float32)) (idFloat32 ((-2.25) : Float32)) (idInt32 ((-1) : Int32))}"
  IO.println s!"f1.3: {f1 (idFloat32 ((-0.0) : Float32)) (idFloat32 (3e38 : Float32)) (idInt32 (2147483647 : Int32))}"
  IO.println s!"f2.0: {f2 (idChar ('\x00' : Char)) (bn 4)}"
  IO.println s!"f2.1: {f2 (idChar ('\x00' : Char)) (bn 5)}"
  IO.println s!"f2.2: {f2 (idChar ('λ' : Char)) (bn 0)}"
  IO.println s!"f2.3: {f2 (idChar ('😀' : Char)) (bn 18)}"
  IO.println s!"f3.0: {f3 (idChar ('a' : Char))}"
  IO.println s!"f3.1: {f3 (idChar ('λ' : Char))}"
  IO.println s!"f3.2: {f3 (idChar ('😀' : Char))}"
  IO.println s!"f3.3: {f3 (idChar ('😀' : Char))}"
  IO.println s!"f4.0: {f4 (idUSize (9223372036854775808 : USize))}"
  IO.println s!"f4.1: {f4 (idUSize (0 : USize))}"
  IO.println s!"f4.2: {f4 (idUSize (0 : USize))}"
  IO.println s!"f4.3: {f4 (idUSize (0 : USize))}"
  IO.println s!"f5.0: {f5 (idFloat32 (0.1 : Float32)) (idChar ('a' : Char)) (bn 12)}"
  IO.println s!"f5.1: {f5 (idFloat32 (1.5 : Float32)) (idChar ('😀' : Char)) (bn 8)}"
  IO.println s!"f5.2: {f5 (idFloat32 (0.1 : Float32)) (idChar ('λ' : Char)) (bn 15)}"
  IO.println s!"f5.3: {f5 (idFloat32 (0.1 : Float32)) (idChar ('λ' : Char)) (bn 12)}"
  IO.println s!"f6.0: {f6 (idInt ((-9223372036854775808) : Int)) (idUInt32 (0 : UInt32)) (idInt32 (2147483647 : Int32)) (idChar ('λ' : Char))}"
  IO.println s!"f6.1: {f6 (idInt ((-1) : Int)) (idUInt32 (4294967295 : UInt32)) (idInt32 (1 : Int32)) (idChar ('a' : Char))}"
  IO.println s!"f6.2: {f6 (idInt ((-1) : Int)) (idUInt32 (2147483648 : UInt32)) (idInt32 ((-1) : Int32)) (idChar ('Z' : Char))}"
  IO.println s!"f6.3: {f6 (idInt (18446744073709551616 : Int)) (idUInt32 (2147483648 : UInt32)) (idInt32 (2147483647 : Int32)) (idChar ('λ' : Char))}"
  IO.println s!"f7.0: {f7 (idInt8 ((-128) : Int8)) (idChar ('λ' : Char)) (idChar ('😀' : Char)) (idUInt8 (127 : UInt8))}"
  IO.println s!"f7.1: {f7 (idInt8 (127 : Int8)) (idChar ('λ' : Char)) (idChar ('😀' : Char)) (idUInt8 (1 : UInt8))}"
  IO.println s!"f7.2: {f7 (idInt8 (127 : Int8)) (idChar ('😀' : Char)) (idChar ('😀' : Char)) (idUInt8 (0 : UInt8))}"
  IO.println s!"f7.3: {f7 (idInt8 (0 : Int8)) (idChar ('Z' : Char)) (idChar ('Z' : Char)) (idUInt8 (1 : UInt8))}"
  IO.println s!"f8.0: {f8 (idFloat32 ((-0.0) : Float32)) (idFloat32 (1e-45 : Float32)) (bn 0)}"
  IO.println s!"f8.1: {f8 (idFloat32 (0.0 : Float32)) (idFloat32 (1.5 : Float32)) (bn 4)}"
  IO.println s!"f8.2: {f8 (idFloat32 ((-2.25) : Float32)) (idFloat32 (0.1 : Float32)) (bn 3)}"
  IO.println s!"f8.3: {f8 (idFloat32 ((-2.25) : Float32)) (idFloat32 (1e-45 : Float32)) (bn 5)}"
  IO.println s!"f9.0: {f9 (idInt32 (0 : Int32))}"
  IO.println s!"f9.1: {f9 (idInt32 (0 : Int32))}"
  IO.println s!"f9.2: {f9 (idInt32 (2147483647 : Int32))}"
  IO.println s!"f9.3: {f9 (idInt32 ((-2147483648) : Int32))}"
  IO.println s!"f10.0: {f10 (idInt64 (0 : Int64)) (idUInt32 (1 : UInt32)) (idUInt16 (65535 : UInt16))}"
  IO.println s!"f10.1: {f10 (idInt64 ((-1) : Int64)) (idUInt32 (0 : UInt32)) (idUInt16 (0 : UInt16))}"
  IO.println s!"f10.2: {f10 (idInt64 ((-9223372036854775808) : Int64)) (idUInt32 (4294967295 : UInt32)) (idUInt16 (0 : UInt16))}"
  IO.println s!"f10.3: {f10 (idInt64 ((-1) : Int64)) (idUInt32 (2147483648 : UInt32)) (idUInt16 (1 : UInt16))}"
  IO.println s!"f11.0: {f11 (idFloat32 ((-2.25) : Float32)) (idInt32 (0 : Int32)) (idChar ('Z' : Char)) (idFloat32 (1e-45 : Float32)) (bn 2)}"
  IO.println s!"f11.1: {f11 (idFloat32 (0.1 : Float32)) (idInt32 (2147483647 : Int32)) (idChar ('a' : Char)) (idFloat32 (1e-45 : Float32)) (bn 14)}"
  IO.println s!"f11.2: {f11 (idFloat32 (1.5 : Float32)) (idInt32 ((-2147483648) : Int32)) (idChar ('😀' : Char)) (idFloat32 ((-2.25) : Float32)) (bn 3)}"
  IO.println s!"f11.3: {f11 (idFloat32 (3e38 : Float32)) (idInt32 (2147483647 : Int32)) (idChar ('a' : Char)) (idFloat32 ((-0.0) : Float32)) (bn 12)}"
  IO.println s!"f12.0: {f12 (idFloat32 (3e38 : Float32))}"
  IO.println s!"f12.1: {f12 (idFloat32 (1e-45 : Float32))}"
  IO.println s!"f12.2: {f12 (idFloat32 ((-0.0) : Float32))}"
  IO.println s!"f12.3: {f12 (idFloat32 ((-0.0) : Float32))}"
  IO.println s!"f13.0: {f13 (idUInt16 (32768 : UInt16)) (idInt64 (9223372036854775807 : Int64))}"
  IO.println s!"f13.1: {f13 (idUInt16 (32768 : UInt16)) (idInt64 (9223372036854775807 : Int64))}"
  IO.println s!"f13.2: {f13 (idUInt16 (1 : UInt16)) (idInt64 ((-9223372036854775808) : Int64))}"
  IO.println s!"f13.3: {f13 (idUInt16 (32768 : UInt16)) (idInt64 (9223372036854775807 : Int64))}"

