/-! Runtime test: a randomly generated control-flow program (gen/rcf.py,
fixed seed): IO functions with mutable variables, for/while loops,
break/continue/return, try/catch/finally (also inside loops), 3-way matches,
closures, calls between functions, arrays and strings; lean2rr turns them into
many join points and state machines.
From the round-7 review, area L (rv7/lowering), check 26 (Rcf6). -/

-- generated by rcf.py seed 6
@[noinline] def f0 (a b : Nat) (arr0 : Array Nat) (s : String) : IO (Nat × String × Array Nat) := do
  let mut v0 := a
  let mut v1 := b
  let mut v2 := a + b
  let mut v3 := 0
  let mut arr := arr0
  let mut str := s
  arr := arr.push arr.size
  for x in arr.toList.take 4 do
    v0 := v0 + x % 13
    v2 := ((7 * 4 % 1000003)) % 1000003
    if str.length % 3 == 1 then
      if arr.size > 4 then
        v3 := v2 + 1
        v2 := ((v0 + v2) - v0)
        str := str ++ toString (v2 % 100)
      else
        str := str ++ toString ((arr.foldl (· + ·) 0 % 997) % 100)
        v0 := v2 + 1
    else
      let mut c365 := 0
      while c365 < 1 do
        c365 := c365 + 1
        str := str ++ toString (str.length % 100)
      if (arr.foldl (· + ·) 0 % 997) < (v1 + v3) then
        v1 := str.length
        v1 := v0
      let mut c383 := 0
      while c383 < 4 do
        c383 := c383 + 1
        arr := arr.push v3
        v1 := ((arr.foldl (· + ·) 0 % 997) - (9223372036854775808 - v0))
        str := str ++ toString (arr.size % 100)
        arr := arr.set! ((v3 - arr.size) % (arr.size + 1)) ((3 - v3) + arr.size)
      if arr.size > 0 then continue
  try
    for x in arr.toList.take 4 do
      v3 := v2 + x % 13
      let g949 := fun (y : Nat) => y * 2 + v3
      v2 := g949 ((arr.foldl (· + ·) 0 % 997)) % 1000003
      v3 := (arr.size) % 1000003
      str := str ++ toString ((arr.size - (v2 + v1)) % 100)
    v2 := (((v1 - v0) * 4 % 1000003)) % 1000003
    if v0 < (arr.foldl (· + ·) 0 % 997) then throw (IO.userError s!"e{v0}")
    v3 := ((arr.foldl (· + ·) 0 % 997)) % 1000003
    v1 := v2
    v3 := str.length
  catch e =>
    str := str ++ toString e
    v0 := (arr.size) % 1000003
  for i in [0:1] do
    v2 := v2 + i
    for i in [0:5] do
      v2 := v1 + i
      arr := arr.set! (v0 % (arr.size + 1)) arr.size
    if str.length % 3 == 0 then IO.println s!"f0 {v0} {str.length}"
  str := str ++ toString ((arr.foldl (· + ·) 0 % 997) % 100)
  arr := arr.push v2
  if (str.length % 3 == 0 || v1 > 12) then IO.println s!"f0 {v3} {str.length}"
  v3 := (arr.size) % 1000003
  return ((v0 + v1 * 3 + v2 * 7 + v3 * 11) % 1000003, (str.take 30).toString, arr.extract 0 8)

@[noinline] def f1 (a b : Nat) (arr0 : Array Nat) (s : String) : IO (Nat × String × Array Nat) := do
  let mut v0 := a
  let mut v1 := b
  let mut v2 := a + b
  let mut v3 := 0
  let mut arr := arr0
  let mut str := s
  for x in arr.toList.take 4 do
    v3 := v0 + x % 13
    v2 := ((1 * 3 % 1000003)) % 1000003
    for x in arr.toList.take 4 do
      v2 := v3 + x % 13
      if (v1 < (arr.foldl (· + ·) 0 % 997) && v0 != v2) then IO.println s!"f1 {v2} {str.length}"
      v0 := v3
      match v0 % 3 with
        | 0 =>
          v1 := v3 + 1
          if v0 < (2 * 2 % 1000003) then break
        | 1 =>
          if arr.size > 3 then break
          v1 := (v2 - v0)
          str := str ++ toString ((v2 - (v0 - v1)) % 100)
        | _ =>
          v2 := v1 + 1
          v1 := v3
      arr := arr.push 0
    v3 := 1
  arr := arr.set! (((arr.foldl (· + ·) 0 % 997) * 1 % 1000003) % (arr.size + 1)) 18446744073709551617
  for i in [0:4] do
    v1 := v2 + i
    v0 := ((arr.foldl (· + ·) 0 % 997)) % 1000003
  v1 := arr.size
  arr := arr.set! (v1 % (arr.size + 1)) 0
  let g666 := fun (y : Nat) => y * 3 + v2
  v2 := g666 (arr.size) % 1000003
  for i in [0:2] do
    v1 := v2 + i
    for x in arr.toList.take 4 do
      v2 := v0 + x % 13
      v2 := (v1) % 1000003
  v2 := ((10 - v0) * 1 % 1000003)
  return ((v0 + v1 * 3 + v2 * 7 + v3 * 11) % 1000003, (str.take 30).toString, arr.extract 0 8)

@[noinline] def f2 (a b : Nat) (arr0 : Array Nat) (s : String) : IO (Nat × String × Array Nat) := do
  let mut v0 := a
  let mut v1 := b
  let mut v2 := a + b
  let mut v3 := 0
  let mut arr := arr0
  let mut str := s
  arr := arr.push arr.size
  v3 := (v2 + v1)
  str := str ++ toString ((str.length - v1) % 100)
  let (r, s2, a2) ← f1 (v2 + 3) arr.size arr str
  v3 := r % 1000003
  str := (s2.take 20).toString
  arr := a2.extract 0 6
  arr := arr.set! (v0 % (arr.size + 1)) 18446744073709551617
  if arr.size > 3 then return (arr.size, str, arr)
  return ((v0 + v1 * 3 + v2 * 7 + v3 * 11) % 1000003, (str.take 30).toString, arr.extract 0 8)

@[noinline] def f3 (a b : Nat) (arr0 : Array Nat) (s : String) : IO (Nat × String × Array Nat) := do
  let mut v0 := a
  let mut v1 := b
  let mut v2 := a + b
  let mut v3 := 0
  let mut arr := arr0
  let mut str := s
  v1 := ((v3 - 10)) % 1000003
  let g257 := fun (y : Nat) => y * 2 + v1
  v2 := g257 (((arr.foldl (· + ·) 0 % 997) * 3 % 1000003)) % 1000003
  for i in [0:1] do
    v2 := v1 + i
    let g637 := fun (y : Nat) => y * 3 + v1
    v0 := g637 (v3) % 1000003
  let g128 := fun (y : Nat) => y * 1 + v0
  v3 := g128 (((v2 * 1 % 1000003) * 3 % 1000003)) % 1000003
  str := str ++ toString (1 % 100)
  str := str ++ toString (str.length % 100)
  arr := arr.set! (v0 % (arr.size + 1)) v1
  return ((v0 + v1 * 3 + v2 * 7 + v3 * 11) % 1000003, (str.take 30).toString, arr.extract 0 8)

@[noinline] def f4 (a b : Nat) (arr0 : Array Nat) (s : String) : IO (Nat × String × Array Nat) := do
  let mut v0 := a
  let mut v1 := b
  let mut v2 := a + b
  let mut v3 := 0
  let mut arr := arr0
  let mut str := s
  match v1 % 3 with
    | 0 =>
      v1 := v1 + 1
      v3 := ((arr.foldl (· + ·) 0 % 997)) % 1000003
    | 1 =>
      str := str ++ toString (arr.size % 100)
    | _ =>
      v1 := (((7 + 0) * 1 % 1000003)) % 1000003
      v3 := ((0 * 3 % 1000003)) % 1000003
  arr := arr.set! (((arr.foldl (· + ·) 0 % 997) - (10 * 2 % 1000003)) % (arr.size + 1)) v2
  v3 := (18446744073709551617) % 1000003
  str := str ++ toString (v3 % 100)
  try
    str := str ++ toString (str.length % 100)
    if ((arr.size < v3 && v1 != arr.size) || v2 > 16) then throw (IO.userError s!"e{v2}")
    for x in arr.toList.take 4 do
      v3 := v0 + x % 13
      v3 := str.length
      for x in arr.toList.take 4 do
        v1 := v0 + x % 13
        v1 := (arr.foldl (· + ·) 0 % 997)
        arr := arr.push v1
        arr := arr.push 7
    let mut c719 := 0
    while c719 < 3 do
      c719 := c719 + 1
      if (arr.size > 1 && (v3 * 2 % 1000003) != arr.size) then return ((str.length - (arr.foldl (· + ·) 0 % 997)), str, arr)
      v0 := (v3) % 1000003
    v1 := (arr.foldl (· + ·) 0 % 997)
  catch e =>
    str := str ++ toString e
    if (9223372036854775808 % 4 == 1 && str.length != (v2 + v2)) then IO.println s!"f4 {v0} {str.length}"
  let g917 := fun (y : Nat) => y * 3 + v1
  v2 := g917 (18446744073709551617) % 1000003
  return ((v0 + v1 * 3 + v2 * 7 + v3 * 11) % 1000003, (str.take 30).toString, arr.extract 0 8)

@[noinline] def f5 (a b : Nat) (arr0 : Array Nat) (s : String) : IO (Nat × String × Array Nat) := do
  let mut v0 := a
  let mut v1 := b
  let mut v2 := a + b
  let mut v3 := 0
  let mut arr := arr0
  let mut str := s
  v0 := v0
  if (arr.size > 0 || v1 > 43) then IO.println s!"f5 {v2} {str.length}"
  try
    arr := arr.push ((v3 + v0) + v2)
    if ((str.length % 3 == 1 || v2 > 15) || v0 > 3) then throw (IO.userError s!"e{v3}")
    for i in [0:3] do
      v0 := v0 + i
      str := str ++ toString (str.length % 100)
      arr := arr.set! (100 % (arr.size + 1)) (arr.size + v0)
      for x in arr.toList.take 4 do
        v1 := v1 + x % 13
        v0 := v2
        arr := arr.set! (arr.size % (arr.size + 1)) (arr.foldl (· + ·) 0 % 997)
    v3 := (((arr.foldl (· + ·) 0 % 997) * 4 % 1000003)) % 1000003
  catch e =>
    str := str ++ toString e
    if str.length % 2 == 0 then
      let (r, s2, a2) ← f1 (arr.foldl (· + ·) 0 % 997) ((arr.foldl (· + ·) 0 % 997) + (arr.foldl (· + ·) 0 % 997)) arr str
      v2 := r % 1000003
      str := (s2.take 20).toString
      arr := a2.extract 0 6
      if arr.size > 1 then
        arr := arr.set! (v3 % (arr.size + 1)) (arr.foldl (· + ·) 0 % 997)
  v2 := (arr.size * 3 % 1000003)
  let g385 := fun (y : Nat) => y * 2 + v2
  v2 := g385 ((arr.foldl (· + ·) 0 % 997)) % 1000003
  v3 := (arr.foldl (· + ·) 0 % 997)
  return ((v0 + v1 * 3 + v2 * 7 + v3 * 11) % 1000003, (str.take 30).toString, arr.extract 0 8)

@[noinline] def f6 (a b : Nat) (arr0 : Array Nat) (s : String) : IO (Nat × String × Array Nat) := do
  let mut v0 := a
  let mut v1 := b
  let mut v2 := a + b
  let mut v3 := 0
  let mut arr := arr0
  let mut str := s
  let mut c296 := 0
  while c296 < 4 do
    c296 := c296 + 1
    arr := arr.set! (arr.size % (arr.size + 1)) (arr.foldl (· + ·) 0 % 997)
    if (str.length % 3 == 1 || v2 > 4) then continue
  let g497 := fun (y : Nat) => y * 1 + v0
  v0 := g497 (arr.size) % 1000003
  let g653 := fun (y : Nat) => y * 1 + v0
  v2 := g653 ((v1 * 4 % 1000003)) % 1000003
  arr := arr.push ((arr.foldl (· + ·) 0 % 997) - (arr.foldl (· + ·) 0 % 997))
  arr := arr.set! (10 % (arr.size + 1)) v2
  return ((v0 + v1 * 3 + v2 * 7 + v3 * 11) % 1000003, (str.take 30).toString, arr.extract 0 8)

@[noinline] def f7 (a b : Nat) (arr0 : Array Nat) (s : String) : IO (Nat × String × Array Nat) := do
  let mut v0 := a
  let mut v1 := b
  let mut v2 := a + b
  let mut v3 := 0
  let mut arr := arr0
  let mut str := s
  for x in arr.toList.take 4 do
    v3 := v2 + x % 13
    v3 := ((v3 + (0 * 2 % 1000003))) % 1000003
  v0 := 9223372036854775808
  arr := arr.set! (str.length % (arr.size + 1)) (arr.size - (v1 * 2 % 1000003))
  try
    arr := arr.set! (v0 % (arr.size + 1)) v2
    let g225 := fun (y : Nat) => y * 2 + v3
    v2 := g225 (v2) % 1000003
    if str.length % 3 == 2 then throw (IO.userError s!"e{v2}")
    v1 := v3
    v3 := 1
  catch e =>
    str := str ++ toString e
    arr := arr.push v1
  arr := arr.set! (str.length % (arr.size + 1)) (arr.foldl (· + ·) 0 % 997)
  v2 := (v3) % 1000003
  if v2 < v2 then
    v0 := (v3 + str.length)
    if str.length % 3 == 0 then
      v0 := (((arr.foldl (· + ·) 0 % 997) - str.length)) % 1000003
      v1 := v2 + 1
      let g307 := fun (y : Nat) => y * 3 + v3
      v0 := g307 (arr.size) % 1000003
      if (v3 + v0) % 4 == 1 then
        v3 := v2 + 1
        str := str ++ toString (((v2 + v3) - str.length) % 100)
        v0 := v0
      else
        arr := arr.set! ((arr.foldl (· + ·) 0 % 997) % (arr.size + 1)) 3
        str := str ++ toString ((18446744073709551617 + 9223372036854775808) % 100)
        arr := arr.set! (v2 % (arr.size + 1)) (v2 * 1 % 1000003)
  else
    for x in arr.toList.take 4 do
      v2 := v0 + x % 13
      arr := arr.set! ((arr.foldl (· + ·) 0 % 997) % (arr.size + 1)) (arr.foldl (· + ·) 0 % 997)
      v1 := ((arr.foldl (· + ·) 0 % 997) + v1)
      arr := arr.push (10 - (v3 * 4 % 1000003))
    v0 := v1
  for i in [0:3] do
    v1 := v2 + i
    v2 := (((arr.foldl (· + ·) 0 % 997) + v1)) % 1000003
    arr := arr.push v3
  return ((v0 + v1 * 3 + v2 * 7 + v3 * 11) % 1000003, (str.take 30).toString, arr.extract 0 8)

@[noinline] def f8 (a b : Nat) (arr0 : Array Nat) (s : String) : IO (Nat × String × Array Nat) := do
  let mut v0 := a
  let mut v1 := b
  let mut v2 := a + b
  let mut v3 := 0
  let mut arr := arr0
  let mut str := s
  arr := arr.set! (v0 % (arr.size + 1)) ((v3 * 3 % 1000003) * 2 % 1000003)
  let g949 := fun (y : Nat) => y * 3 + v3
  v2 := g949 (arr.size) % 1000003
  let (r, s2, a2) ← f3 (str.length - (18446744073709551617 - v2)) (arr.foldl (· + ·) 0 % 997) arr str
  v0 := r % 1000003
  str := (s2.take 20).toString
  arr := a2.extract 0 6
  if v1 < v3 then return (v0, str, arr)
  return ((v0 + v1 * 3 + v2 * 7 + v3 * 11) % 1000003, (str.take 30).toString, arr.extract 0 8)

@[noinline] def f9 (a b : Nat) (arr0 : Array Nat) (s : String) : IO (Nat × String × Array Nat) := do
  let mut v0 := a
  let mut v1 := b
  let mut v2 := a + b
  let mut v3 := 0
  let mut arr := arr0
  let mut str := s
  v0 := v3 + 1
  v2 := arr.size
  arr := arr.set! (v3 % (arr.size + 1)) v0
  v3 := (v1 * 4 % 1000003)
  let (r, s2, a2) ← f6 v0 (arr.size - 3) arr str
  v1 := r % 1000003
  str := (s2.take 20).toString
  arr := a2.extract 0 6
  let mut c579 := 0
  while c579 < 3 do
    c579 := c579 + 1
    for x in arr.toList.take 4 do
      v1 := v2 + x % 13
      let mut c281 := 0
      while c281 < 4 do
        c281 := c281 + 1
        v2 := v1 + 1
        v3 := (v1 + (1 * 1 % 1000003))
        v0 := str.length
        arr := arr.push 100
      v1 := v0
      arr := arr.set! ((v1 + v0) % (arr.size + 1)) (arr.foldl (· + ·) 0 % 997)
  return ((v0 + v1 * 3 + v2 * 7 + v3 * 11) % 1000003, (str.take 30).toString, arr.extract 0 8)

@[noinline] def f10 (a b : Nat) (arr0 : Array Nat) (s : String) : IO (Nat × String × Array Nat) := do
  let mut v0 := a
  let mut v1 := b
  let mut v2 := a + b
  let mut v3 := 0
  let mut arr := arr0
  let mut str := s
  v2 := (v0 - (v3 * 2 % 1000003))
  let g284 := fun (y : Nat) => y * 1 + v3
  v2 := g284 ((arr.foldl (· + ·) 0 % 997)) % 1000003
  v0 := (((v0 + v2) + v1)) % 1000003
  v2 := (v1 * 3 % 1000003)
  let g844 := fun (y : Nat) => y * 2 + v0
  v1 := g844 ((v3 + (arr.foldl (· + ·) 0 % 997))) % 1000003
  return ((v0 + v1 * 3 + v2 * 7 + v3 * 11) % 1000003, (str.take 30).toString, arr.extract 0 8)

@[noinline] def f11 (a b : Nat) (arr0 : Array Nat) (s : String) : IO (Nat × String × Array Nat) := do
  let mut v0 := a
  let mut v1 := b
  let mut v2 := a + b
  let mut v3 := 0
  let mut arr := arr0
  let mut str := s
  arr := arr.set! (((v0 * 4 % 1000003) * 3 % 1000003) % (arr.size + 1)) v1
  v0 := 0
  match v0 % 3 with
    | 0 =>
      v1 := ((v1 + v1) + (v1 * 1 % 1000003))
      arr := arr.push v3
      arr := arr.set! (str.length % (arr.size + 1)) (str.length - arr.size)
      let (r, s2, a2) ← f5 v2 v0 arr str
      v1 := r % 1000003
      str := (s2.take 20).toString
      arr := a2.extract 0 6
    | 1 =>
      match v0 % 3 with
        | 0 =>
          v2 := (v3) % 1000003
          if (v1 * 2 % 1000003) < v0 then
            arr := arr.set! ((arr.foldl (· + ·) 0 % 997) % (arr.size + 1)) v3
            v3 := v3 + 1
          v0 := (18446744073709551617 * 3 % 1000003)
          v3 := (v0) % 1000003
        | 1 =>
          let (r, s2, a2) ← f0 9223372036854775808 0 arr str
          v3 := r % 1000003
          str := (s2.take 20).toString
          arr := a2.extract 0 6
          arr := arr.set! (v0 % (arr.size + 1)) v1
          if arr.size > 1 then
            if (arr.foldl (· + ·) 0 % 997) < str.length then return ((arr.foldl (· + ·) 0 % 997), str, arr)
            str := str ++ toString ((v0 * 4 % 1000003) % 100)
            v2 := v1
            if arr.size > 5 then return (arr.size, str, arr)
          else
            str := str ++ toString ((arr.foldl (· + ·) 0 % 997) % 100)
            arr := arr.push v1
          let g41 := fun (y : Nat) => y * 2 + v0
          v0 := g41 (v2) % 1000003
        | _ =>
          arr := arr.set! (((arr.foldl (· + ·) 0 % 997) - v3) % (arr.size + 1)) str.length
      str := str ++ toString ((arr.size + v0) % 100)
    | _ =>
      v1 := v1
      let mut c649 := 0
      while c649 < 4 do
        c649 := c649 + 1
        arr := arr.push (v2 * 2 % 1000003)
        for x in arr.toList.take 4 do
          v3 := v2 + x % 13
          str := str ++ toString (((v0 + v2) * 2 % 1000003) % 100)
          arr := arr.push (2 - (v2 * 1 % 1000003))
        let g879 := fun (y : Nat) => y * 2 + v1
        v2 := g879 (v1) % 1000003
        v0 := (100) % 1000003
  v3 := v2 + 1
  v2 := (v1) % 1000003
  v0 := v3
  if arr.size % 4 == 1 then
    for i in [0:5] do
      v3 := v1 + i
      arr := arr.push v0
      let mut c415 := 0
      while c415 < 3 do
        c415 := c415 + 1
        v2 := v3
        if arr.size % 2 == 0 then break
    arr := arr.push (arr.foldl (· + ·) 0 % 997)
    v3 := ((v1 + v0) - (arr.foldl (· + ·) 0 % 997))
  else
    for i in [0:4] do
      v3 := v0 + i
      v1 := ((v3 + v2)) % 1000003
      let mut c316 := 0
      while c316 < 2 do
        c316 := c316 + 1
        str := str ++ toString ((arr.foldl (· + ·) 0 % 997) % 100)
        v2 := 10
        arr := arr.set! (((v1 * 3 % 1000003) * 4 % 1000003) % (arr.size + 1)) str.length
        v0 := v0
      let (r, s2, a2) ← f5 v2 3 arr str
      v3 := r % 1000003
      str := (s2.take 20).toString
      arr := a2.extract 0 6
      v3 := 0
    if (arr.size > 4 && (18446744073709551617 * 3 % 1000003) != (18446744073709551617 - v1)) then IO.println s!"f11 {v2} {str.length}"
    v0 := arr.size
    if arr.size % 2 == 1 then
      v3 := arr.size
      str := str ++ toString (3 % 100)
    else
      arr := arr.set! ((v0 - 3) % (arr.size + 1)) (v1 - arr.size)
      arr := arr.set! ((arr.foldl (· + ·) 0 % 997) % (arr.size + 1)) 7
  return ((v0 + v1 * 3 + v2 * 7 + v3 * 11) % 1000003, (str.take 30).toString, arr.extract 0 8)

def main : IO Unit := do
  for (a, b) in [(0, 0), (1, 2), (5, 3), (17, 4), (2^64, 9)] do
    let (r, s, arr) ← f0 a b #[1, 2, 3] "x"
    IO.println s!"f0 {a} {b}: {r} {s} {arr}"
  for (a, b) in [(0, 0), (1, 2), (5, 3), (17, 4), (2^64, 9)] do
    let (r, s, arr) ← f1 a b #[1, 2, 3] "x"
    IO.println s!"f1 {a} {b}: {r} {s} {arr}"
  for (a, b) in [(0, 0), (1, 2), (5, 3), (17, 4), (2^64, 9)] do
    let (r, s, arr) ← f2 a b #[1, 2, 3] "x"
    IO.println s!"f2 {a} {b}: {r} {s} {arr}"
  for (a, b) in [(0, 0), (1, 2), (5, 3), (17, 4), (2^64, 9)] do
    let (r, s, arr) ← f3 a b #[1, 2, 3] "x"
    IO.println s!"f3 {a} {b}: {r} {s} {arr}"
  for (a, b) in [(0, 0), (1, 2), (5, 3), (17, 4), (2^64, 9)] do
    let (r, s, arr) ← f4 a b #[1, 2, 3] "x"
    IO.println s!"f4 {a} {b}: {r} {s} {arr}"
  for (a, b) in [(0, 0), (1, 2), (5, 3), (17, 4), (2^64, 9)] do
    let (r, s, arr) ← f5 a b #[1, 2, 3] "x"
    IO.println s!"f5 {a} {b}: {r} {s} {arr}"
  for (a, b) in [(0, 0), (1, 2), (5, 3), (17, 4), (2^64, 9)] do
    let (r, s, arr) ← f6 a b #[1, 2, 3] "x"
    IO.println s!"f6 {a} {b}: {r} {s} {arr}"
  for (a, b) in [(0, 0), (1, 2), (5, 3), (17, 4), (2^64, 9)] do
    let (r, s, arr) ← f7 a b #[1, 2, 3] "x"
    IO.println s!"f7 {a} {b}: {r} {s} {arr}"
  for (a, b) in [(0, 0), (1, 2), (5, 3), (17, 4), (2^64, 9)] do
    let (r, s, arr) ← f8 a b #[1, 2, 3] "x"
    IO.println s!"f8 {a} {b}: {r} {s} {arr}"
  for (a, b) in [(0, 0), (1, 2), (5, 3), (17, 4), (2^64, 9)] do
    let (r, s, arr) ← f9 a b #[1, 2, 3] "x"
    IO.println s!"f9 {a} {b}: {r} {s} {arr}"
  for (a, b) in [(0, 0), (1, 2), (5, 3), (17, 4), (2^64, 9)] do
    let (r, s, arr) ← f10 a b #[1, 2, 3] "x"
    IO.println s!"f10 {a} {b}: {r} {s} {arr}"
  for (a, b) in [(0, 0), (1, 2), (5, 3), (17, 4), (2^64, 9)] do
    let (r, s, arr) ← f11 a b #[1, 2, 3] "x"
    IO.println s!"f11 {a} {b}: {r} {s} {arr}"

