/-! Runtime test: a random-type fuzzer output (fz/gen.py, seed 7, 6 types):
random nested types over 18 leaves (Nat/Int at the 2^63/2^64 edges, every
fixed width, Float/Float32, Char, Bool, Unit, String, Ordering, a one-field
structure, Fin 5) and nodes List/Array/Option/Prod/Sum/Except/Thunk/Task/a
generic value structure/function types/a field-reordered record/a binary
tree; each value shown directly, through an existential package, through
polymorphic recursion (the uniform instance), in an Array and a List in
uniform code, through an IO.Ref modified by uniform code, and by a
representation-changing Array.map.
From the round-7 review, area R (rv7/repr), generator fz/gen.py (checks
Fz1..Fz9 used 12 types per program; 6 keep the build under a minute). -/

-- generated by gen.py 7 6
structure WN where
  n : Nat
structure W1 (α : Type) where
  v : α
structure P3 (α β : Type) where
  x : β
  y : α
  w : β
inductive Tr (α : Type) where
  | leaf
  | node (l : Tr α) (k : α) (r : Tr α)
def Tr.map {α β : Type} (f : α → β) : Tr α → Tr β
  | .leaf => .leaf
  | .node l k r => .node (l.map f) (f k) (r.map f)
def Tr.mirror {α : Type} : Tr α → Tr α
  | .leaf => .leaf
  | .node l k r => .node r.mirror k l.mirror
def Tr.toList {α : Type} : Tr α → List α
  | .leaf => []
  | .node l k r => l.toList ++ [k] ++ r.toList
structure Pkg where
  α : Type
  v : α
  f : α → α
  s : α → String
@[noinline] def pk (p : Pkg) : String := p.s (p.f (p.f p.v)) ++ " | " ++ p.s p.v
def goX {α β : Type} (n : Nat) (x : α) (b : β) (f : α → α) (k : α → String) : String :=
  match n with
  | 0 => k (f x) ++ " / " ++ k x
  | n+1 => goX n x (b, b) f k
def goA {α β : Type} (n : Nat) (x : Array α) (b : β) (f : α → α) (k : α → String) : String :=
  match n with
  | 0 => let y := x.map f; String.intercalate "; " ((match x[0]? with | some h => y.push h | none => y).toList.map k) ++ s!" #{y.size}"
  | n+1 => goA n x (b, b) f k
def goL {α β : Type} (n : Nat) (x : List α) (b : β) (f : α → α) (k : α → String) : String :=
  match n with
  | 0 => String.intercalate "; " ((x.map f ++ x).map k)
  | n+1 => goL n x (b, b) f k
def goR {α β : Type} (n : Nat) (r : IO.Ref α) (b : β) (f : α → α) : IO Unit :=
  match n with
  | 0 => r.modify f
  | n+1 => goR n r (b, b) f

instance : Inhabited WN := ⟨⟨0⟩⟩
instance {α : Type} [Inhabited α] : Inhabited (W1 α) := ⟨⟨default⟩⟩
instance {α β : Type} [Inhabited α] [Inhabited β] : Inhabited (P3 α β) := ⟨⟨default, default, default⟩⟩
instance {α : Type} : Inhabited (Tr α) := ⟨.leaf⟩
instance {α : Type} [Inhabited α] : Inhabited (Task α) := ⟨Task.pure default⟩
def sh1 : (List WN) → String := fun l => "[" ++ ", ".intercalate (l.map (((fun w => s!"WN {w.n}")) : WN → String)) ++ "]"
def st2 : (List WN) → (List WN) := fun l => (l.map (((fun w => ⟨w.n + 1⟩)) : WN → WN)).reverse
def sh3 : (Task Bool) → String := fun t => "task " ++ ((toString) : Bool → String) t.get
def st4 : (Task Bool) → (Task Bool) := fun t => t.map ((not) : Bool → Bool)
def sh5 : (Task (Task Bool)) → String := fun t => "task " ++ sh3 t.get
def st6 : (Task (Task Bool)) → (Task (Task Bool)) := fun t => t.map st4
def main (args : List String) : IO Unit := do
  let z := args.length
  -- (Fin 5)
  let v0 : (Fin 5) := ((Fin.ofNat 5 (z + 3)) : (Fin 5))
  IO.println ("0 direct " ++ ((toString) : (Fin 5) → String) v0 ++ " " ++ ((toString) : (Fin 5) → String) ((((· + 1)) : (Fin 5) → (Fin 5)) v0))
  IO.println ("0 pkg " ++ pk ⟨(Fin 5), v0, (((· + 1)) : (Fin 5) → (Fin 5)), ((toString) : (Fin 5) → String)⟩)
  IO.println ("0 goX " ++ goX 2 v0 () (((· + 1)) : (Fin 5) → (Fin 5)) ((toString) : (Fin 5) → String))
  IO.println ("0 goA " ++ goA 2 #[v0, (((· + 1)) : (Fin 5) → (Fin 5)) v0] () (((· + 1)) : (Fin 5) → (Fin 5)) ((toString) : (Fin 5) → String))
  IO.println ("0 goL " ++ goL 2 [v0, (((· + 1)) : (Fin 5) → (Fin 5)) v0] () (((· + 1)) : (Fin 5) → (Fin 5)) ((toString) : (Fin 5) → String))
  let r0 ← IO.mkRef v0
  goR 2 r0 () (((· + 1)) : (Fin 5) → (Fin 5))
  IO.println ("0 goR " ++ ((toString) : (Fin 5) → String) (← r0.get))
  -- (List WN)
  let v1 : (List WN) := ([(⟨2^64 + z⟩ : WN), ((((fun w => ⟨w.n + 1⟩)) : WN → WN)) ((⟨2^64 + z⟩ : WN))] : (List WN))
  IO.println ("1 direct " ++ sh1 v1 ++ " " ++ sh1 (st2 v1))
  IO.println ("1 pkg " ++ pk ⟨(List WN), v1, st2, sh1⟩)
  IO.println ("1 goX " ++ goX 2 v1 () st2 sh1)
  IO.println ("1 goA " ++ goA 2 #[v1, st2 v1] () st2 sh1)
  IO.println ("1 goL " ++ goL 2 [v1, st2 v1] () st2 sh1)
  let r1 ← IO.mkRef v1
  goR 2 r1 () st2
  IO.println ("1 goR " ++ sh1 (← r1.get))
  IO.println ("1 map " ++ String.intercalate "; " ((#[v1, st2 v1].map (fun x => (sh1 x, (((· + 1)) : (Fin 5) → (Fin 5)) v0))).toList.map (fun (s, y) => s ++ " " ++ ((toString) : (Fin 5) → String) y)))
  -- Unit
  let v2 : Unit := (() : Unit)
  IO.println ("2 direct " ++ (((fun _ => "()")) : Unit → String) v2 ++ " " ++ (((fun _ => "()")) : Unit → String) (((id) : Unit → Unit) v2))
  IO.println ("2 pkg " ++ pk ⟨Unit, v2, ((id) : Unit → Unit), (((fun _ => "()")) : Unit → String)⟩)
  IO.println ("2 goX " ++ goX 2 v2 () ((id) : Unit → Unit) (((fun _ => "()")) : Unit → String))
  IO.println ("2 goA " ++ goA 2 #[v2, ((id) : Unit → Unit) v2] () ((id) : Unit → Unit) (((fun _ => "()")) : Unit → String))
  IO.println ("2 goL " ++ goL 2 [v2, ((id) : Unit → Unit) v2] () ((id) : Unit → Unit) (((fun _ => "()")) : Unit → String))
  let r2 ← IO.mkRef v2
  goR 2 r2 () ((id) : Unit → Unit)
  IO.println ("2 goR " ++ (((fun _ => "()")) : Unit → String) (← r2.get))
  -- (Fin 5)
  let v3 : (Fin 5) := ((Fin.ofNat 5 (z + 3)) : (Fin 5))
  IO.println ("3 direct " ++ ((toString) : (Fin 5) → String) v3 ++ " " ++ ((toString) : (Fin 5) → String) ((((· + 1)) : (Fin 5) → (Fin 5)) v3))
  IO.println ("3 pkg " ++ pk ⟨(Fin 5), v3, (((· + 1)) : (Fin 5) → (Fin 5)), ((toString) : (Fin 5) → String)⟩)
  IO.println ("3 goX " ++ goX 2 v3 () (((· + 1)) : (Fin 5) → (Fin 5)) ((toString) : (Fin 5) → String))
  IO.println ("3 goA " ++ goA 2 #[v3, (((· + 1)) : (Fin 5) → (Fin 5)) v3] () (((· + 1)) : (Fin 5) → (Fin 5)) ((toString) : (Fin 5) → String))
  IO.println ("3 goL " ++ goL 2 [v3, (((· + 1)) : (Fin 5) → (Fin 5)) v3] () (((· + 1)) : (Fin 5) → (Fin 5)) ((toString) : (Fin 5) → String))
  let r3 ← IO.mkRef v3
  goR 2 r3 () (((· + 1)) : (Fin 5) → (Fin 5))
  IO.println ("3 goR " ++ ((toString) : (Fin 5) → String) (← r3.get))
  IO.println ("3 map " ++ String.intercalate "; " ((#[v3, (((· + 1)) : (Fin 5) → (Fin 5)) v3].map (fun x => (((toString) : (Fin 5) → String) x, st2 v1))).toList.map (fun (s, y) => s ++ " " ++ sh1 y)))
  -- UInt16
  let v4 : UInt16 := ((65535 : UInt16) + z.toUInt16 : UInt16)
  IO.println ("4 direct " ++ ((toString) : UInt16 → String) v4 ++ " " ++ ((toString) : UInt16 → String) ((((· * 3)) : UInt16 → UInt16) v4))
  IO.println ("4 pkg " ++ pk ⟨UInt16, v4, (((· * 3)) : UInt16 → UInt16), ((toString) : UInt16 → String)⟩)
  IO.println ("4 goX " ++ goX 2 v4 () (((· * 3)) : UInt16 → UInt16) ((toString) : UInt16 → String))
  IO.println ("4 goA " ++ goA 2 #[v4, (((· * 3)) : UInt16 → UInt16) v4] () (((· * 3)) : UInt16 → UInt16) ((toString) : UInt16 → String))
  IO.println ("4 goL " ++ goL 2 [v4, (((· * 3)) : UInt16 → UInt16) v4] () (((· * 3)) : UInt16 → UInt16) ((toString) : UInt16 → String))
  let r4 ← IO.mkRef v4
  goR 2 r4 () (((· * 3)) : UInt16 → UInt16)
  IO.println ("4 goR " ++ ((toString) : UInt16 → String) (← r4.get))
  IO.println ("4 map " ++ String.intercalate "; " ((#[v4, (((· * 3)) : UInt16 → UInt16) v4].map (fun x => (((toString) : UInt16 → String) x, ((id) : Unit → Unit) v2))).toList.map (fun (s, y) => s ++ " " ++ (((fun _ => "()")) : Unit → String) y)))
  -- (Task (Task Bool))
  let v5 : (Task (Task Bool)) := ((Task.spawn fun _ => ((Task.spawn fun _ => ((z == 0) : Bool)) : (Task Bool))) : (Task (Task Bool)))
  IO.println ("5 direct " ++ sh5 v5 ++ " " ++ sh5 (st6 v5))
  IO.println ("5 pkg " ++ pk ⟨(Task (Task Bool)), v5, st6, sh5⟩)
  IO.println ("5 goX " ++ goX 2 v5 () st6 sh5)
  IO.println ("5 goA " ++ goA 2 #[v5, st6 v5] () st6 sh5)
  IO.println ("5 goL " ++ goL 2 [v5, st6 v5] () st6 sh5)
  let r5 ← IO.mkRef v5
  goR 2 r5 () st6
  IO.println ("5 goR " ++ sh5 (← r5.get))
  IO.println ("5 map " ++ String.intercalate "; " ((#[v5, st6 v5].map (fun x => (sh5 x, (((· + 1)) : (Fin 5) → (Fin 5)) v3))).toList.map (fun (s, y) => s ++ " " ++ ((toString) : (Fin 5) → String) y)))

